name: "GitHub Copilot"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  copilot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: github/copilot@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
